name: btelnyy-lifesteal
main: me.btelnyy.lifesteal.LifeSteal
version: ${project.version}
api-version: 1.18
commands:
   sethealth:
      description: set max health of a player
      usage: /sethealth <player> <amount>
      permission: btelnyy.command.setmaxhealth 
   givehealth:
      description: give some of your health to another player
      usage: /givehealth <player> <amount>
      permission: btelnyy.command.givehealth