name: MorePvp
version: '${project.version}'
main: me.loaf.morepvp.MorePvp
api-version: 1.18
commands:
   zappywand:
      description: ZAP ZAP
      usage: /zappywand <player>
      permission: btelnyy.command.givehealth
   boomboom:
      description: ZAP ZAP
      usage: /boomboom
      permission: btelnyy.command.givehealth 
   yeeter:
      description: ZAP ZAP
      usage: /yeeter
      permission: btelnyy.command.givehealth
   buzzy:
      description: ZAP ZAP
      usage: /buzzy
      permission: btelnyy.command.givehealth
   CommandSetHealth:
      description: ZAP ZAP
      usage: /sethealth <player>
      permission: btelnyy.command.givehealth 
   die:
      description: ZAP ZAP
      usage: /die <player>
      permission: btelnyy.command.givehealth 
   swap:
      description: ZAP ZAP
      usage: /swap
      permission: btelnyy.command.givehealth 
   